
# export LAYERS_EXP_SERVICE=my-layers-exp
service: ${self:custom.serviceName}

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: eu-west-1
  logRetentionInDays: 7
  versionFunctions: false
  environment:
    loggingLevel: info

custom:
  serviceName: ${env:LAYERS_EXP_SERVICE, "layers-exp"}
  libsLayerServiceName: ${env:LAYERS_EXP_LAYER_SERVICE, "layers-exp-layer"}
  libsLayerVersion: 5 # The latest version of the layer (gotta be a better way)
  libsLayerArn:
    Fn::Join:
      - ''
      - - 'arn:aws:lambda:'
        - Ref: 'AWS::Region'
        - ':'
        - Ref: 'AWS::AccountId'
        - ':layer:'
        - ${self:custom.libsLayerServiceName}
        - '-'
        - ${sls:stage}
        - '-'
        - 'Libs'
        - ':'
        - ${self:custom.libsLayerVersion}

functions:
  hello:
    handler: src/lambda/hello.handler
    layers:
    # Can't use Fn::ImportValue as it means the layer cannot be updated.
      - ${self:custom.libsLayerArn}
