
# export LAYERS_EXP_SERVICE=my-layers-exp
service: ${self:custom.serviceName}

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: eu-west-1
  logRetentionInDays: 7
  versionFunctions: false
  environment:
    loggingLevel: info

custom:
  serviceName: ${env:LAYERS_EXP_SERVICE, "layers-exp"}
  libsLayerServiceName: ${env:LAYERS_EXP_LAYER_SERVICE, "layers-exp-layer"}

functions:
  hello:
    handler: src/lambda/hello.handler
    layers:
      - ${cf:${self:custom.libsLayerServiceName}-${sls:stage}.LibsLayerExport}
