
service: peter-layers-exp

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: eu-west-1
  logRetentionInDays: 7
  versionFunctions: false

functions:
  hello:
    handler: src/lambda/hello.handler
